### ISSUE TITLE
Wrong log placeholder for the bool type

### ISSUE THREAD

**Issue by elipavlov** [slok/kubewebhook#101]
Here used format placeholder `%q` which probably not applicable for the `bool` type.

https://github.com/slok/kubewebhook/blob/v2.0.0/pkg/webhook/validating/webhook.go#L108-L112

In logs it looks like:
```
... Webhook validating review finished with %!q(bool=true) result ...
```

**Comment by slok** [comment]
@elipavlov thanks for the issue!

Should be fixed now :)
