### ISSUE TITLE
kubernetes v1.21.3 tls error

### ISSUE THREAD

**Issue by tianshimoyi** [slok/kubewebhook#109]
The tls error is displayed when the k8s version is v1.21.3, but it is displayed normally when the k8s version is v1.17.12

The error is：
remote error: tls: bad certificate

**Comment by tianshimoyi** [comment]
Solved, there is a problem with the creation of the certificate script. If the go version of k8s is greater than or equal to 15 you need to create a certificate that uses the extended SAN

**Comment by shenxianghong** [comment]
> to create a certificate that uses the extended SAN

how to create a certificate that uses the extended SAN?
