### ISSUE TITLE
Better error / documenting error

### ISSUE THREAD

**Issue by innovia** [slok/kubewebhook#33]
I am using the mutation webhook and currently returning an error like so:

```golang
fmt.Fprintf(os.Stderr, "error serving webhook: %s", err)

```

however, the pod event looks like this:

```console
24m         Warning   FailedCreate        replicaset/hello-secrets-78445d48c9   Error creating: Internal error occurred: failed calling webhook "pods.vault-secrets-webhook.admission.server.com": an error on the server ("{\"response\":{\"uid\":\"97705fda-61c0-11e9-ad59-0800272e4a1f\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Error getting vault address - make sure you set the annotation\"}}}") has prevented the request from succeeding
```

is there any way we can only show the error.status.message instead of this ugly json?

**Comment by slok** [comment]
Hey @innovia!

I don't know if understood ok, but, what you are saying is that you are using Kubernetes go client to create a resource, the kubernetes APIserver returns you an error because of a webhook and you want to print prettier error instead of all the ugly json?

If this is the case... Although this is not related to Kubewebhook and more related to Kubernetes admission webhooks itself, you can do something like this:

```go
import (
    //...
    apierrors "k8s.io/apimachinery/pkg/api/errors"
    //...
)

func myfn() {
    //...
    msg := err.Error()
    if sErr, ok := err.(*apierrors.StatusError); ok {
        msg = sErr.ErrStatus.Status
    }
    fmt.Fprintf(os.Stderr, "error serving webhook: %s", msg)
    //...
}
```

**Comment by slok** [comment]
Oh! I understood now, I leave the previous response in case anyone has that question. You mean a event in Kubernetes that is printed by Kubectl right?, that messages are handled by Kubctl (if it did the action), or a controller/operator if they set the message on the event directly (as a raw string) , AFAIK until they have better support for errors messages from the apiserver (for example using the method in the previous comment), we can't do anything.

I would ned to make more research and try a few things, but I think that Kubewebhook here can't do anything more

**Comment by innovia** [comment]
@slok yes in the event itself the returned response is a JSON string, i'll try what you suggested

thank you!

**Comment by jesusvazquez** [comment]
It had been some time since you opened this issue @innovia. If this is no longer an issue for you, would it be OK that we close it?

**Comment by innovia** [comment]
Yes sure go ahead and close it

Thank you

**Comment by slok** [comment]
Thanks @innovia, like @jesusvazquez says, it been a while since this problem and things have changed, in Kubewebhook, apiserver and Kubernetes Go libs:

An example:

```
kubectl -n monitoring  apply -f /tmp/grafana.yaml                                                                                                               
Error from server: error when creating "/tmp/grafana.yaml": admission webhook "ingress-validation-webhook.slok.dev" denied the request: ingress host is invalid: host grafana2.valhalla.slok2.dev is not a valid host
Error from server: error when creating "/tmp/grafana.yaml": admission webhook "ingress-validation-webhook.slok.dev" denied the request: ingress is invalid: ingress rules length should be 1, got: 2
```

Closing then, thanks both of you.
