### ISSUE TITLE
Check if request is dry run

### ISSUE THREAD

**Issue by mg03** [slok/kubewebhook#43]
Hi

I am using the example for multiwebhook as a starting point and in the Mutate function (in file examples/multiwebhook/pkg/webhook/mutating/mutator.go) i added the following code at line 26 :

```
if whcontext.IsAdmissionRequestDryRun(ctx) {
                 m.logger.Infof("Dry Run")
		return false, nil
	}
```
I tested by kubectl apply --dry-run test.yaml, but this code doesnt seem to do print the info message .

Is the above a correct way to check whether dry run or not?

**Comment by slok** [comment]
Hi! sorry for the delay, Didn't receive Github notifications.

First of all, regarding the framework, yes, that's the correct way of checking if is dry run.

Second, the Dry run is received from the APIserver [Check this](https://github.com/kubernetes/api/blob/924612ff3bca0e127b87d7c9ba26abf3c20e0f47/admission/v1beta1/types.go#L105), so you would need to set up the webhook registration in dry run, so the apiserver does not persist the webhook mutations and validations. But that configuration has nothing to do with kubewebhook itself.

Best!
