### ISSUE TITLE
fix jsonpath create wrong patch

### ISSUE THREAD

**Issue by luodw** [slok/kubewebhook#44]
Hi,  I have use kubewebhook to create k8s webhook service to do crd resource defaults and validates.  I found a bug in mutating webhook service  when create json patch in https://github.com/slok/kubewebhook/blob/master/pkg/webhook/mutating/webhook.go#L147. 

It does not create json patch as expected, because it use origJSON and mutatedJSON to create json patch.  The right way to create json patch is using  AdmissionReview.Request.Object.Raw and mutatedJSON, the reason is follows:
1. The origJSON may be different from AdmissionReview.Request.Object.Raw，because AdmissionReview.Request.Object.Raw -->unmarshaled to --> origOBJ --> marshaled to --> origJSON,  so if AdmissionReview.Request.Object.Raw has some attr missing，origJSON will has a init value;
2. As some attrs,  origJSON has init value but AdmissionReview.Request.Object.Raw has none , so when create json patch, it will has wrong operation,  maybe add, but replace;

kubernetes-sigs/controller-runtime  also use AdmissionReview.Request.Object.Raw  to create json patch
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/admission/defaulter.go#L74

**Comment by marvelm** [comment]
Hi @luodw Could you point me to your fork with the fix for this issue?

**Comment by luodw** [comment]
> Hi @luodw Could you point me to your fork with the fix for this issue?

https://github.com/slok/kubewebhook/pull/45/files

**Comment by slok** [comment]
I'm updating Kubernetes Versions and the integration tests, and when I have everything up to date I'll try reproducing this win some unit tests and/or integration tests and fix it.

Does this only happen with CRDs?

Could you describe a situation where this happens? so I can reproduce?

**Comment by luodw** [comment]
> Hi there!
> 
> I'm updating Kubernetes Versions and the integration tests, and when I have everything up to date I'll try reproducing this win some unit tests and/or integration tests and fix it.
> 
> Does this only happen with CRDs?
> 
> Could you describe a situation where this happens? so I can reproduce?
> 
> Thank you!
 
I use kubewebhook to write crd resource defaults and validates, and it happens  when I create a instance without some attrs, and webhook do the defaults for the attrs;

For example,  my crd resource  has below attrs, 
type HelloCRDSpec struct {
        Containers []SidecarContainer `json:"containers,omitempty"`
        Volumes []corev1.Volume `json:"volumes,omitempty"`
        Strategy HelloCRDUpdateStrategy `json:"strategy,omitempty"`
}
type HelloCRDUpdateStrategy struct {
	RollingUpdate *RollingUpdateSidecarSet `json:"rollingUpdate,omitempty"`
}
type RollingUpdateSidecarSet struct {
	MaxUnavailable *intstr.IntOrString `json:"maxUnavailable,omitempty"`
}

When I create HelloCRD instance without Strategy，so also, there is no strategy attr in rawJSON.  If kubewebhook unmarshal the rawJSON, the oldObj which is unmarshaled from rawJSON will have init value for Strategy.  

If oldJSON := json.Marshal(oldObj), oldJSON will not equal to rawJSON, as oldJSON has strategy attr and rawJSON has no strategy attr; 

If patch := jsonpatch.CreatePatch(origJSON, mutatedJSON), it will has a item which like {"op": "replace",  "path": "", "value":""}
but if patch := jsonpatch.CreatePatch(rawJSON, mutatedJSON), it will has a item which like {"op": "add", "path":"". "value":""}

I don't know if I have make myself clear?

**Comment by slok** [comment]
Oh, I see, what you mean is that when I unmarshal the received JSON data into a Kubernetes Go instance, the unmarshalling process adds default values to some of the fields that have initialization, and when using this unmarshalled object to create the patch it ends in a _modification_ instead of a _addition_ right?

**Comment by luodw** [comment]
> Oh, I see, what you mean is that when I unmarshal the received JSON data into a Kubernetes Go instance, the unmarshalling process adds default values to some of the fields that have initialization, and when using this unmarshalled object to create the patch it ends in a _modification_ instead of a _addition_ right?

yeah, that's the point.

**Comment by slok** [comment]
@luodw @marvelm New release with the fix: https://github.com/slok/kubewebhook/releases/tag/v0.7.0

Sorry for the bug! and thanks for reporting and fixing it!
