### ISSUE TITLE
about CRD

### ISSUE THREAD

**Issue by PualrDwade** [slok/kubewebhook#70]
I need to control the access of CRD use mutatewebhook. It seems that this framework will not work,does it support CRD?

**Comment by slok** [comment]
Hi @PualrDwade!

What is the problem you are having?

Kubewebhook supports CRDs, you can check the types (`dynamic` and `static`)of webhooks [here](https://github.com/slok/kubewebhook#static-and-dynamic-webhooks).

**TL;DR:** For CRDs is better the Static webhooks, if you use Dynamic webhooks, the type is unknown and will fallback to [`Unstructured`](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#Unstructured)

There are integration tests for CRDs also. Check this Webhook for a CRD:

https://github.com/slok/kubewebhook/blob/9df65e34ec7ac175252e6a212420147e49715aa8/test/integration/webhook/mutating_test.go#L195-L209

Hope it helps.

**Comment by slok** [comment]
Closing, if you continue with doubts reopen this or open a new issue.
