### ISSUE TITLE
can not decode pod object when deleting pod

### ISSUE THREAD

**Issue by wucanhao** [slok/kubewebhook#71]
I am using k8s 14 version, and set up a delete pod webhook. By using v10.0 kubewebhook, but getting a empty pod object like:

`Pod{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:PodSpec{Volumes:[]Volume{},Containers:[]Container{},RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},},}`

**Comment by wucanhao** [comment]
the problem still exist while using older version of kubewebhook

**Comment by slok** [comment]
> the problem still exist while using older version of kubewebhook

Do you mean Kubernetes?

**Comment by wucanhao** [comment]
> > the problem still exist while using older version of kubewebhook
> 
> Do you mean Kubernetes?

No, I have try an older version of kubewebhook, according to the Compatibility matrix.

**Comment by slok** [comment]
But you said you were using `v10.0`

**Comment by wucanhao** [comment]
> But you said you were using `v10.0`

Sorry, maybe I do not express clearly.  I mean I have tried different version of kubewebhook and the problem still exist.

**Comment by slok** [comment]
Yes, you need to update Kubewebhook to the new versions, we only maintain one branch of updates.
