### ISSUE TITLE
How to get Verb/UserInfo/.... when implementing a validate webhook

### ISSUE THREAD

**Issue by aholic** [slok/kubewebhook#76]
the validator interface contains`Validate(ctx context.Context, obj metav1.Object)`
it means i can implement my logic with the resource, nothing else

if i have some logic for the verb, i can't determine what's the verb of this request, i can't get it.....

i think there should be a way for me to get the  `AdmissionReview` struct, but i can't find any examples

**Comment by slok** [comment]
Hi @aholic

You can get the request from the context using [`context.GetAdmissionRequest`](https://pkg.go.dev/github.com/slok/kubewebhook@v0.11.0/pkg/webhook/context#GetAdmissionRequest).

**Comment by slok** [comment]
@aholic Did this solve your problems? can I close it?
